# اسم التطبيق
spring.application.name=inventory-management

# رقم المنفذ الذي سيعمل عليه المشروع
server.port=8081

# رابط الاتصال بقاعدة بيانات MySQL (تقدر تتحكم فيها عن طريق environment variables)
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# اسم مستخدم قاعدة البيانات
spring.datasource.username=root

# كلمة مرور قاعدة البيانات (تقدر تغيّرها عن طريق متغير بيئة DB_PASSWORD إذا لزم)
spring.datasource.password=Inventory123
# برنامج تشغيل MySQL (JDBC Driver)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# يقوم Hibernate بتحديث الجداول تلقائياً دون حذف البيانات
spring.jpa.hibernate.ddl-auto=update
# يعرض أوامر SQL التي ينفذها Spring Boot في الـ Console
spring.jpa.show-sql=true

# يجعل أوامر SQL مرتبة وسهلة القراءة في الـ Console
spring.jpa.properties.hibernate.format_sql=true

# يحدد أن قاعدة البيانات المستخدمة هي MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ==========================
# Actuator Configuration
# ==========================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Inventory Management System
info.app.version=1.0
info.app.description=Spring Boot Inventory Management Project
